---
abstract: 'generate a dashboard of information about a selection of CPAN dists'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Dashboard
requires:
  CPAN::ReverseDependencies: 0
  CPAN::Testers::WWW::Reports::Query::AJAX: 0
  Carp: 0
  HTTP::Tiny: 0
  JSON: 0
  Moo: 0
  PAUSE::Packages: 0
  PAUSE::Permissions: 0
  perl: 5.010
version: 0.01
